import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createVehicleSystem,validateVehicleProfiles} from '../src/vehicle-system.js';
import {combinationDynamics,driveAccelScaleAtSpeed} from '../src/truck-trailer.js';

const profiles=validateVehicleProfiles();
assert.equal(profiles.ok,true,profiles.errors?.join('\n'));
const vs=createVehicleSystem({initialId:'wrx'});
const fleet=vs.list();
assert.equal(fleet.length,9,'7 passenger cars + 2 articulated trucks expected');
assert.ok(fleet.some(p=>p.id==='semi_6x4'));
assert.ok(fleet.some(p=>p.id==='semi_cabover_glb'));
assert.equal(vs.select('semi_cabover_glb'),true);
assert.equal(vs.active.visual.type,'semi-tractor-glb');
assert.equal(vs.active.trailer.lengthM,16.15);
assert.equal(vs.physics.axles.length,3);
assert.equal(vs.physics.massKg,8600);
assert.equal(vs.physics.coupling.type,'fifth-wheel');
const combo=combinationDynamics({tractor:vs.physics,trailer:vs.active.trailer});
assert.equal(combo.totalMassKg,27100);
assert.ok(driveAccelScaleAtSpeed({tractor:vs.physics,trailer:vs.active.trailer,speedMps:8})>.5);
const glb=new URL('../src/assets/cabover_micro.glb',import.meta.url);
const st=fs.statSync(glb);
assert.ok(st.size>10000,'GLB asset should be a real binary model, not placeholder');
const head=fs.readFileSync(glb).subarray(0,4).toString('ascii');
assert.equal(head,'glTF');
const truckSource=fs.readFileSync(new URL('../src/truck-trailer.js',import.meta.url),'utf8');
assert.match(truckSource,/GLTFLoader/);
assert.match(truckSource,/semi_cabover_glb/);
assert.match(truckSource,/new URL\('\.\/assets\/cabover_micro\.glb',import\.meta\.url\)/);
console.log('V21.24.0 CAB-OVER GLB QA: PASS');
console.log(`fleet: ${fleet.length} vehicles; GLB: ${st.size} bytes; combination: ${combo.totalMassKg} kg`);
